name: Deploy Changes
run-name: Deploy changes to production
concurrency: production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Login to container registry
        run: docker login -u ${{secrets.CONTAINER_REGISTRY_USERNAME}} -p ${{secrets.CONTAINER_REGISTRY_PASSWORD}} ${{secrets.CONTAINER_REGISTRY_URL}}
      
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Calculate Image Tags
        run: echo "ImgTags=$(date +'%Y%m%d%H%M');latest" >> $GITHUB_ENV
      
      - name: Publish Image to Registry
        run: dotnet publish --no-restore /t:PublishContainer -p ContainerImageTags='$ImgTags' -p ContainerRegistry=${{secrets.CONTAINER_REGISTRY_URL}}

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
      - name: Deploy Image to Azure WebApp
        run: curl "${{secrets.DEPLOY_IMAGE_WEBHOOK}}"